# Generated by Django 3.1.3 on 2020-12-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendenceInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('adharno', models.BigIntegerField()),
                ('phoneno', models.BigIntegerField()),
                ('role', models.TextField()),
                ('sallery', models.FloatField()),
                ('dob', models.DateField()),
                ('education', models.TimeField()),
                ('workexperience', models.IntegerField()),
                ('recuritmentdate', models.DateField()),
                ('medicalhistory', models.TextField(blank=True)),
            ],
        ),
    ]
