# Generated by Django 3.1.3 on 2020-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='education',
            field=models.TextField(blank=True),
        ),
    ]
