# Generated by Django 3.1.3 on 2021-01-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201214_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendenceinfor',
            name='adharno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employeeinfo'),
            preserve_default=False,
        ),
    ]
